// Generated by CoffeeScript 1.4.0
(function() {

  define(["doh/runner"], function(doh) {
    return doh.register('HelloDojoButton', require.toUrl("App/tests/Views/testHelloDojoButton.html"), 999999);
  });

}).call(this);
