// Generated by CoffeeScript 1.4.0
(function() {

  define(["dojo/_base/declare", "dojo/on", "dijit/_WidgetBase"], function(declare, on_, _WidgetBase) {
    return declare("HelloDojoButton", [_WidgetBase], {
      message: null,
      postCreate: function() {
        var _this = this;
        return on_(this.domNode, 'click', function() {
          return $(_this.domNode).after($('<p />').text(_this.message));
        });
      }
    });
  });

}).call(this);
